### ISSUE TITLE
Odnośnie polskiego tłumaczenia

### ISSUE THREAD

**Issue by bandithedoge** [MatesOo/en-JOYcon-AiO-Pack#1]
Nie polecam zamiany języka innego niż angielski, ponieważ niektóre gry ustawiają swój język na podstawie ustawień konsoli. A ponieważ technicznie ustawiony jest język holenderski, nie chcemy użytkowników narzekających na gry po holendersku. Poza tym zamiana innego języka utrudnia aktualizowanie moda.

**Comment by bandithedoge** [comment]
Jeszcze jedno. Jeżeli w nowym FW zmiany są zaznaczone jako 0, nie oznacza to, że pliki nie zostały zmienione. Sporo błędów zostało poprawionych. Nintendo czasem usuwa, a czasem dodaje nowe linijki, więc nieuważne wybieranie zaktualizowanych plików może prowadzić do błędów (np. puste linijki).

**Comment by MatesOo** [comment]
Jesteśmy świadomi, że gry będą uruchamiały się po holendersku gdy wybierze się język polski. Nie uważam tego za problem ponieważ w ustawieniach atmosfery można wymusić dla danego titleid inny język niż systemowy. Mam zamiar napisać o tym na wiki.
Angielskiego nie chcemy ruszać, te ustawienie jest bezpieczniejsze z kilku względów. Raz LayeredFS jest zbyt delikatne, więc zamienianie domyślnego angielskiego za polski może w przyszłości spowodować niepożądane problemy, podobnie jak moduły, którymi trzeba tasować przy update fw/atmo. Dwa nie każdy potrzebuje języka polskiego. Trzy, możliwa popularyzacja AIO poza kraj.

**Comment by bandithedoge** [comment]
Rozumiem. Wciąż jednak proszę o aktualizowanie wszystkich plików tłumaczenia, a nie tylko tych, w których liczba linijek różni się od wersji poprzedniej.

**Comment by MatesOo** [comment]
Aktualnie w AiO występuje wersja tłumaczenia 1.1, niczego nie wybierałem paka była wrzucona w całości. Duplikaty są automatycznie pomijane przez githuba.
